### ISSUE TITLE
this.$router is undefined

### ISSUE THREAD

**Issue by cbrhex** [framework7io/framework7-template-vue-simple#1]
Hi. I need make a redirect in main.vue, but this.$router is undefined. How can I do that? thx.

**Comment by auzadventure** [comment]
You are probably trying to access it in your Main View. this.router is only available in the child component  views.

To access it in the main.vue, use $f7.views.main.router

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
