### ISSUE TITLE
When I build an apk file using cordova, the apk file shows blank screen on device

### ISSUE THREAD

**Issue by alapanme** [framework7io/framework7-template-vue-simple#2]
I have created a project on this template. Now I build an apk file using cordova. Now when I am installing and running the android file on the device, I am getting an blank screen.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
