### ISSUE TITLE
Material theme navbar not shown for opened page

### ISSUE THREAD

**Issue by rashnk** [framework7io/framework7-template-vue-simple#3]
I changed app.js to use material css as material:true
and changed to link material css file in index.html , when the about-page is opened navbar not updated or not showing in front of existing navbar, this issue occur only when using material css

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
